
# Copyright 2018 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
ARG MLRUN_PYTHON_VERSION=3.7

FROM python:${MLRUN_PYTHON_VERSION}-slim

ENV PIP_NO_CACHE_DIR=1

RUN apt update && apt -y upgrade && apt install -y \
    ca-certificates \
    gcc \
    git-core \
    && update-ca-certificates --fresh \
    && apt clean \
    && apt autoremove \
    && rm -rf /var/lib/apt/lists/*

ENV SSL_CERT_DIR /etc/ssl/certs

RUN mkdir -p /var/run/sshd && \
    # Allow OpenSSH to talk to containers without asking for confirmation
    cat /etc/ssh/ssh_config | grep -v StrictHostKeyChecking > /etc/ssh/ssh_config.new && \
    echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config.new && \
    mv /etc/ssh/ssh_config.new /etc/ssh/ssh_config

COPY ./dockerfiles/mlrun/requirements.txt /tmp/mlrun-image-requirements.txt
COPY ./requirements.txt /tmp/requirements.txt
RUN python -m pip install --upgrade pip~=20.2.0 \
    && python -m pip install \
    -r /tmp/requirements.txt \
    -r /tmp/mlrun-image-requirements.txt \
    && rm -f \
    /tmp/mlrun-image-requirements.txt \
    /tmp/requirements.txt

WORKDIR /tmp/mlrun
COPY . /tmp/mlrun
RUN python -m pip install /tmp/mlrun[complete] \
    && rm -rf /tmp/mlrun
